baseURL = "https://kahila.github.io/" # Must end with splash
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Kahila"

staticDir = ["themes/Niello/static", "static"]

theme = "Niello"

[languages]
	[languages.en]
		title = "{CodeTrace} - Discover Issues, Share Solutions."
		languageCode = "en-us"
		LanguageName = "ğŸ‡ºğŸ‡¸EN"
		contentDir = "content/en"
		weight = 1
		[[languages.en.menus.main]]
			name = 'Home'
			pageRef = '/'
			weight = 1
		[[languages.en.menus.main]]
			name = 'Categories'
			pageRef = '/categories'
			weight = 2
		[[languages.en.menus.main]]
			name = 'Tags'
			pageRef = '/tags'
			weight = 3
		[[languages.en.menus.main]]
			name = 'Contact'
			pageRef = '/contact'
			weight = 4
	[languages.zh]
		title = "{ç é€”è½¨è¿¹} - å‘ç°é—®é¢˜ï¼Œåˆ†äº«è§£å†³."
        	languageCode = "zh-cn"
        	LanguageName = "ğŸ‡¨ğŸ‡³CN"
        	contentDir = "content/zh"
        	weight = 2
		[[languages.zh.menus.main]]
			name = 'é¦–é¡µ'
			pageRef = '/'
			weight = 1
		[[languages.zh.menus.main]]
			name = 'æ–‡ç« åˆ†ç±»'
			pageRef = '/categories'
			weight = 2
		[[languages.zh.menus.main]]
			name = 'æ ‡ç­¾'
			pageRef = '/tags'
			weight = 3
		[[languages.zh.menus.main]]
			name = 'è”ç³»æˆ‘ä»¬'
			pageRef = '/contact'
			weight = 4
        
[params]
[params.google]
	google_ad_client = "ca-pub-******"  //Optional, replace ca-pub-****** with your content
	ga4 = "G-******" //Optional, replace G-****** with your Google Analytics GA4
[params.bannershowcase]
	categories = ["AI"]
	limit = 2
[params.email]
	contact = "angularcorp@outlook.com"
[params.ignore]
	categories = ["privacy", "terms", "archives", "cookie"]
[params.license]
	copyright = "&#xA9; 2019 ~ 2025 by guangmean. All Rights Reserved."
[params.share]
	sharethis = "******"  // Optional, Add hou ShareThis appid here
[params.disqus]
	shortname = "******"	// Optional, Disqus Comment Short Name

[outputs]
  home = ["HTML", "JSON"]
    